services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - 3308:3306
    environment:
      - "MYSQL_ROOT_USER=root"
      - "MYSQL_ROOT_PASSWORD=123teste"
      - "MYSQL_DATABASE=taskdb_docker"
    networks:
      - local-db-net

  server:
    container_name: app_container
    image: demo:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8443:8443
    depends_on:
      - mysqldb
    networks:
      - local-db-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/taskdb_docker?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

networks:
    local-db-net:
